# Generated by Django 4.1.7 on 2023-03-29 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500, unique=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Comment",
            },
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("All", "All"), ("Restricted", "Restricted")],
                        default="Restricted",
                        max_length=12,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Author", "Author"),
                            ("Manager", "Manager"),
                            ("Contributor", "Contributor"),
                        ],
                        default="Contributor",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contributor",
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=2500)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("Bug", "Bug"),
                            ("Improvement", "Improvement"),
                            ("Task", "Task"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ToDo", "ToDo"),
                            ("InProgress", "InProgress"),
                            ("Done", "Done"),
                        ],
                        default="ToDo",
                        max_length=12,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Issue",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Back-End", "Back-End"),
                            ("Front-End", "Front-End"),
                            ("IOS", "IOS"),
                            ("Android", "Android"),
                        ],
                        default="Back-End",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
            },
        ),
    ]
